export const patentsSeed = {
  heroIntro:
    '42+ patents registered and completed in spatial analysis, XR technologies, and AI-driven systems across US and Korea.',
  licensingHeading: 'Interested in Technology Licensing?',
  licensingBody:
    'Our patented technologies are available for licensing and collaboration. Contact us to explore partnership opportunities.',
  stats: {
    total: 42,
    international: 3,
    korean: 20,
    pending: 19,
  },
  items: [
    {
      id: '1',
      title:
        'Tourist Accommodation Recommendation Method and System Using Multi-Criteria Decision-Making and Augmented Reality',
      number: 'US11,816,804B2',
      country: 'US',
      date: 'Nov 14, 2023',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi, Somaieh Rokhsaritalemi',
      status: 'registered' as const,
      type: 'international' as const,
    },
    {
      id: '2',
      title: 'IoT-Based Approach Method for Learning Geometric Shapes in Early Childhood and Device Thereof',
      number: '18/821,509',
      country: 'US',
      date: 'Aug 30, 2024',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi, et al.',
      status: 'pending' as const,
      type: 'international' as const,
    },
    {
      id: '3',
      title: 'Semantic Information Retrieval Method for Augmented Reality Domain and Device Thereof',
      number: '18/818,158',
      country: 'US',
      date: 'Aug 28, 2024',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi, Tamer Abuhmed',
      status: 'pending' as const,
      type: 'international' as const,
    },
    {
      id: '4',
      title:
        'Geospatial Information System-Based Modeling Approach for Leakage Management in Urban Water Distribution Networks',
      number: '10-2356500',
      country: 'Korea',
      date: 'Jan 24, 2022',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi',
      status: 'registered' as const,
      type: 'korean' as const,
    },
    {
      id: '5',
      title:
        'Groundwater Potential Mapping Using Integrated Ensemble of Three Bivariate Statistical Models with Random Forest and Logistic Tree Models',
      number: '10-2307898',
      country: 'Korea',
      date: 'Sept 27, 2021',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi',
      status: 'registered' as const,
      type: 'korean' as const,
    },
    {
      id: '6',
      title:
        'Method and Apparatus for Enhancing Response Coordination through Assessment of Response Network Structural Dynamics',
      number: '10-22089060',
      country: 'Korea',
      date: 'Jan 22, 2021',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi',
      status: 'registered' as const,
      type: 'korean' as const,
    },
    {
      id: '7',
      title: 'Context-Aware Route Finding Algorithm for Self-Driving Tourists Using Ontology',
      number: '10-2148349',
      country: 'Korea',
      date: 'Aug 20, 2020',
      inventors: 'Abolghasem Sadeghi-Niaraki, Soo-Mi Choi',
      status: 'registered' as const,
      type: 'korean' as const,
    },
    {
      id: '8',
      title: 'Method and Device for Generating a Wildfire Vulnerability Map Using Artificial Intelligence',
      number: '10-2706021',
      country: 'Korea',
      date: 'Sept 09, 2024',
      inventors: 'Soo-Mi Choi, Abolghasem Sadeghi-Niaraki',
      status: 'registered' as const,
      type: 'korean' as const,
    },
  ],
} as const;
